[workspace]
name = "In-Context-Learning-in-Multi-Agent-Interdependent-Decision-Making"
version = "0.1.0"
channels = ["conda-forge"]
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-64",
    "osx-arm64",
    "win-64",
]


[dependencies]
python = ">=3.12"


[pypi-dependencies]
in-context-learning-in-multi-agent-interdependent-decision-making = { path = ".", editable = true }

